let jokes = ["What do you call a fish wearing a bowtie? Sofishticated",
"How does a penguin build its house? Igloos it together",
"What do you call a boomerang that doesn’t come back? A stick",
"What do you call a snowman with a six pack? An abdominal snowman",
"Why did the coffee file a police report? It got mugged",
"How do you make a tissue dance? You put a little boogie in it",
"What do you call cheese that isn’t yours? Nacho cheese",
"What do you get when you cross a snowman and a vampire? Frostbite",
"What do you call a bear with no teeth? A gummy bear",
"What do you call a dog that can tell time? A watch dog",
"What do you call a fish that wears a crown? A king fish",
"What do you call a snake that works for the government? A civil serpent",
"What do you call a cow that has a twitch? Beef jerky",
"What do you call a camel in a drought? A dry humper",
"What do you call a man with a rubber toe? Roberto",
"What do you call a line of rabbits hopping backwards? A receding hare line",
"What do you call a monkey in a minefield? A baboom",
"What do you call a horse that likes to dance? A disco neigh",
"What do you call a sheep that does karate? A lamb chop",
"What do you call a pig that does yoga? A hamasana",
"What do you call a bird that’s afraid to fly? Chicken",
"What do you call a deer with no eyes? No eye deer",
"What do you call a fly without wings? A walk",
"What do you call a woman who sets fire to her bills? Bernadette",
"What do you call a fish that wears glasses? A see fish",
"What do you call a nun who walks in her sleep? A roamin’ Catholic",
"What do you call a pasta that is sick? Macaroni and sneeze",
"What do you call a magician who loses his magic? Ian",
"What do you call a duck that gets all A’s? A wise quacker",
"What do you call a hippie’s wife? Mississippi",
"What do you call a can opener that doesn’t work? A can’t opener",
"What do you call a lemon that can sing? A lemonade",
"What do you call a crocodile that likes to bowl? An alley gator",
"What do you call a man who never farts in public? A private tutor",
"What do you call a potato that smokes weed? A baked potato",
"What do you call a lawyer who is good at math? A sue-doku solver",
"What do you call a sheep that is always quiet? A shhh-eep",
"What do you call a spider that has no legs? A raisin",
"What do you call a bear that has no fur? Bare",
"What do you call a skunk that flies? A smellicopter",
"What do you call a worm that sings? A glow worm",
"What do you call a rabbit that has fleas? Bugs bunny",
"What do you call a donkey that is good at math? A smart ass",
"What do you call a frog that likes to read? A book hopper",
"What do you call a lion that is well-dressed? A dandy lion",
"What do you call a flower that runs on electricity? A power plant",
"What do you call a dog that likes to paint? A picasso",
"What do you call a cat that is good at knitting? A purr-l",
"What do you call a mouse that is good at chess? A check-mate"];

let length = jokes.length;
let jokeBox = document.querySelector('.jokeBox').firstElementChild;
let button = document.getElementsByTagName('button')[0];
button.addEventListener('click',()=>{
  let joke = Math.floor(Math.random() * length);
  jokeBox.innerHTML = `"${jokes[joke]}"`;
});